title: Startpage
theme: light
background: 
  image: https://images.unsplash.com/photo-1528837516156-0a7225a43641?q=80&w=3433&auto=format&fit=crop
  brightness: 100

bookmarks:
  - name: Github
    abbr: GH
    url: https://github.com

  - name: Reddit
    abbr: RD
    url: https://reddit.com

  - name: JV/Aabenraa
    abbr: JV
    url: https://jv.dk/aabenraa

  - name: Hacker News
    abbr: HN
    url: https://news.ycombinator.com

  - name: DMI
    abbr: DM
    url: https://dmi.dk

  - name: Facebook
    abbr: FB
    url: https://facebook.com

  - name: Youtube
    abbr: YT
    url: https://youtube.com

  - name: DR/TV
    abbr: DR
    url: https://dr.dk/tv

  - name: Twitter
    abbr: TW
    url: https://twitter.com/i/lists/1583402559238283265

  - name: Humans of Newyork
    abbr: HU
    url: https://humansofnewyork.com